<MenuScreen>:
    BoxLayout:
        Button:
            text: 'Goto game'
            on_press: root.manager.current = 'game'
        Button:
            text: 'Quit'
            on_press: app.stop()

<GameScreen>:
    canvas:
        Color:
            rgba: 1, 0, 0, 1
        Rectangle:
            size: 100, 100
            pos: 200, 200

<BoxWidget>:
    source: self.source_dir
    size_hint: (None, None)
    pos: self.position
    size: self.size_variable


